services:
  # FastAPI 애플리케이션
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      # 외부 PostgreSQL 데이터베이스 연결 정보
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_URL_NO_SSL=${POSTGRES_URL_NO_SSL}
      - POSTGRES_PRISMA_URL=${POSTGRES_PRISMA_URL}
    volumes:
      - .:/app
    restart: unless-stopped 